import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import type { Inputs, LineItem, ScenarioMetrics } from "@/types/budget";

interface EmailViewProps {
  state: { inputs: Inputs; lineItems: LineItem[] };
  metrics: ScenarioMetrics[];
}

export function EmailView({ state, metrics }: EmailViewProps) {
  const totalCosts = state.lineItems.reduce(
    (sum, li) => sum + li.unitCost * li.quantity,
    0
  );

  const topScenarios = [...metrics]
    .sort((a, b) => b.profit - a.profit)
    .slice(0, 6);

  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Badger Budget Summary</title>
</head>
<body style="font-family: Arial, sans-serif; font-size: 14px; line-height: 1.5; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
  <h1 style="font-size: 24px; margin-bottom: 8px;">Badger Budget Summary</h1>
  <p style="color: #666; margin-bottom: 24px;">Email-friendly summary. Use the app for full interactive analysis.</p>

  <h2 style="font-size: 18px; margin-top: 24px; margin-bottom: 8px;">Inputs</h2>
  <table style="width: 100%; border-collapse: collapse; margin-bottom: 24px;">
    <tr><td style="padding: 6px 0; border-bottom: 1px solid #eee;">Max Occupancy</td><td style="padding: 6px 0; border-bottom: 1px solid #eee;">${state.inputs.maxOccupancy}</td></tr>
    <tr><td style="padding: 6px 0; border-bottom: 1px solid #eee;">Staff Count</td><td style="padding: 6px 0; border-bottom: 1px solid #eee;">${state.inputs.staffCount}</td></tr>
    <tr><td style="padding: 6px 0; border-bottom: 1px solid #eee;">Ticket Prices</td><td style="padding: 6px 0; border-bottom: 1px solid #eee;">$${state.inputs.ticketPrices.proposedPrice1} / $${state.inputs.ticketPrices.proposedPrice2} / $${state.inputs.ticketPrices.proposedPrice3} (Staff: $${state.inputs.ticketPrices.staffPrice1} / $${state.inputs.ticketPrices.staffPrice2} / $${state.inputs.ticketPrices.staffPrice3})</td></tr>
    <tr><td style="padding: 6px 0; border-bottom: 1px solid #eee;">Day Pass</td><td style="padding: 6px 0; border-bottom: 1px solid #eee;">$${state.inputs.dayPassPrice} × ${state.inputs.dayPassesSold} = $${(state.inputs.dayPassPrice * state.inputs.dayPassesSold).toLocaleString()}</td></tr>
  </table>

  <h2 style="font-size: 18px; margin-top: 24px; margin-bottom: 8px;">Budget Total</h2>
  <p style="font-size: 18px; font-weight: bold;">$${totalCosts.toLocaleString("en-US", { minimumFractionDigits: 2 })}</p>

  <h2 style="font-size: 18px; margin-top: 24px; margin-bottom: 8px;">Top Scenarios by Profit</h2>
  <table style="width: 100%; border-collapse: collapse;">
    <tr style="background: #f5f5f5;">
      <th style="padding: 8px; text-align: left;">Scenario</th>
      <th style="padding: 8px; text-align: right;">Revenue</th>
      <th style="padding: 8px; text-align: right;">Profit</th>
      <th style="padding: 8px; text-align: right;">Cost/Person</th>
    </tr>
    ${topScenarios
      .map(
        (m) =>
          `<tr>
            <td style="padding: 8px; border-bottom: 1px solid #eee;">${m.scenarioKey}</td>
            <td style="padding: 8px; border-bottom: 1px solid #eee; text-align: right;">$${m.revenue.toLocaleString()}</td>
            <td style="padding: 8px; border-bottom: 1px solid #eee; text-align: right; color: ${m.profit >= 0 ? "#22c55e" : "#ef4444"};">$${m.profit.toLocaleString()}</td>
            <td style="padding: 8px; border-bottom: 1px solid #eee; text-align: right;">$${m.costPerAttendee.toFixed(0)}</td>
          </tr>`
      )
      .join("")}
  </table>

  <p style="margin-top: 24px; color: #666; font-size: 12px;">Generated by Badger Budget Dashboard</p>
</body>
</html>
`;

  return (
    <div className="space-y-4">
      <p className="text-muted-foreground text-sm">
        Copy the HTML below or open in a new tab to share via email.
      </p>
      <Textarea
        readOnly
        className="h-64 font-mono text-xs"
        value={html}
      />
      <Button
        type="button"
        onClick={() => {
          const w = window.open("", "_blank");
          if (w) {
            w.document.write(html);
            w.document.close();
          }
        }}
      >
        Open in new tab
      </Button>
    </div>
  );
}
