export const queryKeys = {
  budgets: ["budgets"] as const,
  budget: (id: string) => ["budget", id] as const,
  scenarios: ["scenarios"] as const,
  scenario: (id: string) => ["scenario", id] as const,
  events: ["events"] as const,
  event: (id: string) => ["event", id] as const,
  members: ["members"] as const,
  member: (id: string) => ["member", id] as const,
  contacts: (params: Record<string, unknown>) => ["contacts", params] as const,
  contact: (id: string) => ["contact", id] as const,
  contactTags: ["contacts", "tags"] as const,
  mailingLists: ["mailingLists"] as const,
  mailingList: (id: string) => ["mailingList", id] as const,
  mailingListPreview: (id: string) => ["mailingList", id, "preview"] as const,
  mailingListStats: (id: string) => ["mailingList", id, "stats"] as const,
  mailingListIncluded: (id: string, page: number, limit: number, q?: string) =>
    ["mailingList", id, "included", page, limit, q ?? ""] as const,
  mailingListMembers: (id: string) => ["mailingList", id, "members"] as const,
  mailingBatches: ["mailingBatches"] as const,
  mailingBatch: (id: string) => ["mailingBatch", id] as const,
} as const;
